### ISSUE TITLE
no such target '@pybind11//:osx'

### ISSUE THREAD

**Issue by yockie** [pybind/pybind11_bazel#23]
env:
os：centos7
bazel：0.24

when I build with bazel, some errors occurred：
build aborted: no such target '@pybind11//:osx': target 'osx' not declared in package '' defined by /root/.cache/bazel/_bazel_root/624d315a340482468c06182680e982d6/external/pybind11/BUILD

I am a newer of pybind11_bazel. how can I fix it？

thank you very much.

**Comment by yockie** [comment]
Does someone have any idea how to fix it?

**Comment by chuckx** [comment]
Can you provide a bit more context?

For instance, the Bazel command you're executing, the relevant portions of your WORKSPACE and BUILD files, etc.?

**Comment by mchinen** [comment]
FYI, this error happened to me when I accidentally named pybind11_bazel as pybind11 in git_repository.

**Comment by wzheng21** [comment]
The workaround that works for me:
1. Comment out `@pybind11//:osx` from `PYBIND_DEPS`
2. In your WORKSPACE file, manual build your own pybind11 (with maybe `new_git_repository` from github or even `new_local_repository` if your /usr/include already has pybind11 installed).
3. In `pybind_extension` targets, add the deps using **your own** pybind11

**Comment by mchinen** [comment]
...and I hit this again.  This time it was because I had tensorflow workspace import functions in my WORKSPACE, which imported an out of date pybind11_bazel, causing the new one with the `osx` config_settings to not exist in the build_file that the http_repository used without warning.  I fixed it by adding my new http_repository for pybind11/pybind11_bazel before the TF workspace functions.

**Comment by junyer** [comment]
This issue is obsolete, I believe, given the removal of the `osx` config setting in favour of using `@platforms//os:osx` directly.
