### ISSUE TITLE
clang -Bsymbolic linkopts

### ISSUE THREAD

**Issue by M-Kerr** [pybind/pybind11_bazel#3]
Inside build_defs.bzl on line 43, the pybind_extension linkopts -Bsymbolic flag is incompatible with MacOS clang.
Removing the flag seems to fix the issue. I'd submit a fix, however I don't know how to fix it generically where -Bsymbolic remains in the case of other compilers.

**Comment by TheButlah** [comment]
I also have this issue

**Comment by M-Kerr** [comment]
This issue was fixed with PR #7.

**Comment by TheButlah** [comment]
@M-Kerr where did you remove the flag? In the macro definition?

**Comment by M-Kerr** [comment]
The pybind_extension macro inside the build_defs.bzl file

**Comment by TheButlah** [comment]
Yep, removing the extension works for me on clang! However, I would really like to know if this can be removed on gcc as well, or if not, then how to make it select which flags based on compiler.

**Comment by TheButlah** [comment]
Update: This still spews out a bunch of warnings like
>ld: warning: direct access in function 'pybind11::class_<devices:
:realsense::v2::IFrameset>::class_<>(pybind11::handle, char const*)' from file 'bazel-out/darwin-fastbuild/bin/devices/realsense/_objs/realsense_py.so/pybindings.o' to global weak symbol 'typeinfo for devices::realsense::v2::IFrameset' from file 'bazel-out/darwin-fastbuild/bin/devices/realsense/librealsense.a(misc_cc49943026644f8c7b9188229fb28ede.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.

Furthermore, I get this error when attempting to import in python:
> import realsense_py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: arg(): could not convert default argument 'align_to: std::__1::optional<devices::realsense::v2::CameraType>' in method '<class 'realsense_py.Config'>.__init__' into a Python object (type not registered yet?)

**Comment by TheButlah** [comment]
Update #2: I'm dumb
I still get the warnings, but they don't seem to impact the actual build. The second error when importing is because I forgot to `#include <pybind11/stl.h>` in my bindings.cpp file

**Comment by chuckx** [comment]
I believe #10 addresses this issue. Please chime in if further refinements may be necessary.

**Comment by TheButlah** [comment]
@chuckx I'm not #10 actually works, or if it does it seems to be using deprecated features and an extraneous compile flag. I don't even know if `darwin` is a valid `cpu` value. I will submit a PR using the recommended technique to turn it off on darwin.

**Comment by TheButlah** [comment]
Submitted a PR: See #12

**Comment by M-Kerr** [comment]
Resolved with PR #12
