### ISSUE TITLE
pybind11_bazel is incompatible with Windows cmd

### ISSUE THREAD

**Issue by amatveiakin** [pybind/pybind11_bazel#30]
I cannot build a pybind11 target from Windows command prompt. I'm trying to run `bazel build` and get:

```
Error in fail: Python Configuration Error: --define PYTHON_BIN_PATH='C:\ProgramData\Anaconda3\python.exe' is not executable. Is it the python binary?
```

There is a perfectly valid python binary under the path specified, and the same build finishes successfully when `bazel build` is run from git bash. So I assume this is a sign of incompatibility between pybind11_bazel and cmd.

Running bazel from bash on Windows is considered an anti-pattern: https://docs.bazel.build/versions/master/windows.html#running-bazel-msys2-shell-vs-command-prompt-vs-powershell.
Is it possible to make pybind11_bazel cmd-compatible?

**Comment by charles-sun0v0** [comment]
I met the same problem as you. So is there any idea to solve it?

**Comment by Mizux** [comment]
The issue is you need to escape `\` aka using `\\`.
e.g. if you have installed python 3.10 using the windows installer at https://www.python.org/downloads/release/python-3104/
`in  C:\python-310-64`.
then you would want to set the env. variable `PYTHON_BIN_PATH` using the `System Properties`/`Environment Variables...`/`User variables for <username>` then create the variable pointing to the `python.exe`  and ... it won't work !!!

workaround: replace all `\` by `\\` then it should find the executable.

note: On my way to fix the source code and do some tests so it will just work "out of the windows box"...

**Comment by junyer** [comment]
As of the [v2.11.1.bzl.2](https://github.com/pybind/pybind11_bazel/releases/tag/v2.11.1.bzl.2) release, pybind11_bazel uses rules_python and `python_configure.bzl` no longer exists. (Hi, @Mizux!)
