### ISSUE TITLE
python_configure fails with python 3.10

### ISSUE THREAD

**Issue by jeongukjae** [pybind/pybind11_bazel#37]
Since `distutils` package is deprecated and [this rule uses `distutils` to get python include path](https://github.com/pybind/pybind11_bazel/blob/72cbbf1fbc830e487e3012862b7b720001b70672/python_configure.bzl#L247), `python_configure` fails with python 3.10.

stderr:
```
DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
```

Related links:
* https://www.python.org/dev/peps/pep-0632/
* migration advice in pep 0632: https://www.python.org/dev/peps/pep-0632/#migration-advice
* https://github.com/pybind/pybind11_bazel/blob/72cbbf1fbc830e487e3012862b7b720001b70672/python_configure.bzl#L247
* My project using this rule and python 3.10: https://github.com/jeongukjae/nori-clone/runs/4776043260?check_suite_focus=true#step:5:53

**Comment by jeongukjae** [comment]
migration advice in pep 0632: https://www.python.org/dev/peps/pep-0632/#migration-advice

**Comment by jeongukjae** [comment]
here's my solution: https://github.com/jeongukjae/nori-clone/commit/3e4fc321d570ce5dcabccdf1bab1144d839405a7

**Comment by mchinen** [comment]
@jeongukjae 's solution resolved this issue for me.

**Comment by Mizux** [comment]
related to:
* pybind/pybind11#3764

**Comment by jblespiau** [comment]
I had the same issue, and as a workaround, we submitted

https://github.com/pybind/pybind11_bazel/commit/b7698470858505a34a7966d188f14425181a3b52

It  won't fix the fact that, because of the warning, it wont be able to infer the include-paths, but it is making it possible to set  `PYTHON_LIB_PATH`, and that will be used instead.

This way, one can tell the `python_configure` which Python to use by doing e.g.:

```
export PYTHON_BIN_PATH=`which python3`
export PYTHON_LIB_PATH=`python3 -c "import sysconfig; print(sysconfig.get_path('include'))"`
```

which works with Python3.

At the moment, pybind11_bazel is no longer owned by a specific team, so maintenance falls behind.

A proper way to fix that would be to look at the version, split it by ".", convert it into a sequence number, and if it's > [3, 10], execute `import sysconfig; print(sysconfig.get_path('include'))"` instead of the current code being executed.

If someone has time to do a PR, I suppose we could submit it.

**Comment by jblespiau** [comment]
Solved by https://github.com/pybind/pybind11_bazel/pull/44

Thanks for reporting.
