### ISSUE TITLE
solve "Problem getting python include path." in python3.10 

### ISSUE THREAD

**Issue by 0x00-pl** [pybind/pybind11_bazel#42]
in python3.10
```
>>> from distutils import sysconfig
<stdin>:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
<stdin>:1: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
```
this warning will break function `_get_python_include`.

**Comment by 0x00-pl** [comment]
hotfox: add `--action_env=PYTHONWARNINGS=ignore` into bazel flags.

**Comment by OpenSpiel** [comment]
I had the same issue, and as a workaround, we submitted

https://github.com/pybind/pybind11_bazel/commit/b7698470858505a34a7966d188f14425181a3b52

It  won't fix the fact that, because of the warning, it wont be able to infer the include-paths, but it is making it possible to set  `PYTHON_LIB_PATH`, and that will be used instead.

This way, one can tell the `python_configure` which Python to use by doing e.g.:

```
export PYTHON_BIN_PATH=`which python3`
export PYTHON_LIB_PATH=`python3 -c "import sysconfig; print(sysconfig.get_path('include'))"`
```

which works with Python3.

At the moment, pybind11_bazel is no longer owned by a specific team, so maintenance falls behind.

A proper way to fix that would be to look at the version, split it by ".", convert it into a sequence number, and if it's > [3, 10], execute `import sysconfig; print(sysconfig.get_path('include'))"` instead of the current code being executed.

If someone has time to do a PR, I suppose we could submit it.

**Comment by jblespiau** [comment]
This was solved by https://github.com/pybind/pybind11_bazel/pull/44

Thanks for reporting.
