### ISSUE TITLE
error loading package '': Extension 'python_configure.bzl' has errors

### ISSUE THREAD

**Issue by hkhkq** [pybind/pybind11_bazel#70]
how to fix it？bazel version is too old？
ERROR: /root/.cache/bazel/_bazel_root/20b0440996eece92fec12c85fbefa37a/external/pybind11_bazel/python_configure.bzl:485:13: name 'module_extension' is not defined
ERROR: /root/.cache/bazel/_bazel_root/20b0440996eece92fec12c85fbefa37a/external/pybind11_bazel/python_configure.bzl:488:22: name 'tag_class' is not defined

**Comment by junyer** [comment]
> how to fix it？bazel version is too old？

That may indeed be the case, yes, but since you haven't disclosed the version of Bazel that you are using, I can only suggest trying either `--experimental_enable_bzlmod` (Bazel 5) or `--enable_bzlmod` (Bazel 6). Having said that, even before Bzlmod was enabled by default in Bazel 7, using the `module_extension()` and `tag_class()` functions shouldn't have caused errors, I believe, which leads me to wonder further about the version of Bazel that you are using.
