### ISSUE TITLE
Linker error when using ld.gold

### ISSUE THREAD

**Issue by hofbi** [pybind/pybind11_bazel#94]
The new flags introduced with https://github.com/pybind/pybind11_bazel/pull/90 result in a linker error for the examples:

```shell
/usr/bin/ld.gold: undefs: unknown -z option
```

**Comment by hofbi** [comment]
@rwgk I can see this issue is mentioned in several commits in https://github.com/pybind/pybind11_abseil. Does this mean you are able to reporduce it there?

**Comment by rwgk** [comment]
Yes, but I took a shortcut and simply pinned the pybind11_bazel version:

https://github.com/pybind/pybind11_abseil/commit/d25d7b3f3aaab9fbce8d58800ce981d4c2d43972

What crossed my mind (but I will not have a chance to work on myself for sure, unfortunately):

It would be great if there was

* a GitHub Action here in pybind11_bazel that
* git clones pybind11_abseil (which should always be in working condition, because we have pre-submit testing Google-internally, including pybind11_abseil GitHub actions),
* then runs the same bazel test commands as we're running in the pybind11_abseil GitHub Actions,
* **except that the pybind11_bazel version is unpinned.**

Which is essentially what you'd have to do now (just locally) to reproduce the issue.

Ideally repeat with pybind11_protobuf.

**Comment by hofbi** [comment]
Sounds good. This information is super helpful for #96.

**Comment by hofbi** [comment]
@rwgk I created #98 revertig the issue introduced by #90.

**Comment by jiawen** [comment]
Agreed on all points. @rwgk I've never set up GitHub Actions before but I'd like to give it a go. `pybind11_abseil`, `pybind11_bazel`, and `pybind11_protobuf` are all mutually related and it'd be good have CI for them.

**Comment by rwgk** [comment]
> Agreed on all points. @rwgk I've never set up GitHub Actions before but I'd like to give it a go. `pybind11_abseil`, `pybind11_bazel`, and `pybind11_protobuf` are all mutually related and it'd be good have CI for them.

I only know a little bit myself, about GitHub actions. There isn't much to it getting started: simply add a file with some name, e.g. `.github/workflows/ci.yml`. You could start by copying a pybind11_abseil or pybind11_protobuf .yml file. Often I also look at the [upstream pybind11 .yml files](https://github.com/pybind/pybind11/tree/master/.github/workflows), those are very well maintained.

I found this quite useful:

https://github.github.io/actions-cheat-sheet/actions-cheat-sheet.pdf

There is more documentation that's pretty good. Spending half an hour or so just to look around and know where things are is probably a productivity booster.

**Comment by hofbi** [comment]
https://github.com/bazel-contrib/rules_oci/blob/main/.github/workflows/ci.yaml or similar repos in this group are also good examples.

**Comment by jiawen** [comment]
@hofbi: type in the issue title? `lg.gold` -> `ld.gold`?

**Comment by hofbi** [comment]
Good catch, thanks
